export enum FieldType {
    Text = 'text',
    Email = 'email',
    Tel = 'tel',
    Password = 'password',
    Search = 'search',
    Number = 'number',
    Color = 'color',
    Range = 'range',
    Textarea = 'textarea',
    Html = 'html',
    Date = 'date',
    Time = 'time',
    DateTime = 'datetime',
    File = 'file',
    Image = 'image',
    Select = 'select',
    Check = 'check',
    Switch = 'switch',
    Calc = 'calc',
    Card = 'card',
}