export enum ValidationCode {
    MinStringLength = 'min-str',
    MinNumber = 'min-num',
    MaxStringLength = 'max-str',
    MaxNumber = 'max-num',
    Email = 'email',
    Empty = 'empty',
    EqualTo = 'equal-to',
    MinNumbers = 'min-numbers',
    MaxNumbers = 'max-numbers',
    MinChars = 'min-chars',
    MaxChars = 'max-chars',
    MinUpperChars = 'min-upper-chars',
    MaxUpperChars = 'max-upper-chars',
    MinLowerChars = 'min-lower-chars',
    MaxLowerChars = 'max-lower-chars',
    MinSpecialChars = 'min-special-chars',
    MaxSpecialChars = 'max-special-chars',
}