export enum WebElementType {
    LktText = 1,
    LktTextBox = 2,
    LktLayout = 3,
    LktLayoutBox = 4,
    LktTextAccordion = 5,
    LktLayoutAccordion = 6,
    LktTextBanner = 7,
    LktLayoutBanner = 8,
    LktAnchor = 9,
    LktButton = 10,
    LktHeader = 11,
    LktIcon = 12,
    LktIcons = 13,
    LktImage = 14,
}