export enum WebElementType {
    LktAnchor = 'lkt-anchor',
    LktLayoutAccordion = 'lkt-layout-accordion',
    LktTextAccordion = 'lkt-text-accordion',
    LktLayoutBox = 'lkt-layout-box',
    LktTextBox = 'lkt-text-box',
    LktLayoutBanner = 'lkt-layout-banner',
    LktTextBanner = 'lkt-text-banner',
    LktButton = 'lkt-button',
    LktLayout = 'lkt-layout',
    LktHeader = 'lkt-header',
    LktIcon = 'lkt-icon',
    LktIcons = 'lkt-icons',
    LktImage = 'lkt-image',
    LktText = 'lkt-text',
}